[package]
name = "native-effects"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
strip = true
lto = true

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.20.0"
rand = "0.8.5"
image = "0.24.5"
